name = "bolt-diy-worker" # Replace with your worker's name
type = "javascript" # Change if you're using TypeScript or another language

account_id = "91d06794cbcaf7f6c8827add68ab3e36" # Replace with your Cloudflare account ID
workers_dev = true # Set to false if using custom domains
route = "" # Specify a route if needed
zone_id = "" # Specify your zone ID if deploying to a custom domain
